version: "3.8"
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
#      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=automatic_irrigation_system
    networks:
      backend:



networks:
  backend:
    driver: bridge