FROM alpine:3 as download

RUN apk add --no-cache wget
RUN wget https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez


FROM rabbitmq:3.11
WORKDIR /opt/rabbitmq/plugins

COPY --from=download rabbitmq_delayed_message_exchange-3.11.1.ez  rabbitmq_delayed_message_exchange.ez

RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange rabbitmq_management