version: "3.8"
services:

  app:
    container_name: app
#    image: company/automaticirrigationsystem:0.0.1-SNAPSHOT
    build:
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/automatic_irrigation_system
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8081:8081"
    networks:
      backend:
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
#      - MYSQL_USER=root # by default
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=automatic_irrigation_system
    networks:
      backend:

  rabbitmq:
    build:
      dockerfile: Dockerfile-rabbitmq
    container_name: rabbitMQ
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      backend:

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
      - KEYCLOAK_USER=admin
      - DB_VENDOR=h2
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    command:
      - "-b 0.0.0.0"
#      - "-Djboss.socket.binding.port-offset=5"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8080:8080"
    networks:
      backend:


networks:
  backend:
    driver: bridge